# Generated by Django 4.2.30 on 2026-06-24 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="品牌名称"
                    ),
                ),
                (
                    "reputation",
                    models.FloatField(default=70.0, verbose_name="品牌声誉(0-100)"),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=10,
                        verbose_name="营销预算(万元)",
                    ),
                ),
                (
                    "aggressiveness",
                    models.FloatField(default=0.5, verbose_name="激进程度(0-1)"),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("premium", "高端策略"),
                            ("aggressive", "激进促销"),
                            ("branding", "品牌优先"),
                            ("stable", "稳健经营"),
                        ],
                        default="stable",
                        max_length=20,
                        verbose_name="经营策略",
                    ),
                ),
                (
                    "target_sales",
                    models.IntegerField(default=10, verbose_name="目标销量(件/天)"),
                ),
                (
                    "total_sales",
                    models.IntegerField(default=0, verbose_name="累计销量"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="累计营收(元)",
                    ),
                ),
                (
                    "market_share",
                    models.FloatField(default=25.0, verbose_name="市场份额(%)"),
                ),
                (
                    "logo_emoji",
                    models.CharField(
                        default="🏢", max_length=10, verbose_name="品牌图标"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d", max_length=10, verbose_name="品牌色(hex)"
                    ),
                ),
            ],
            options={
                "verbose_name": "品牌Agent",
                "verbose_name_plural": "品牌Agent",
            },
        ),
        migrations.CreateModel(
            name="CustomerAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="顾客名称")),
                ("age", models.IntegerField(default=25, verbose_name="年龄")),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("student", "学生"),
                            ("white_collar", "白领"),
                            ("engineer", "工程师"),
                            ("freelancer", "自由职业"),
                            ("executive", "管理层"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="职业",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=5000,
                        max_digits=10,
                        verbose_name="月度预算(元)",
                    ),
                ),
                (
                    "preference",
                    models.CharField(
                        choices=[
                            ("gaming", "游戏玩家"),
                            ("office", "办公商务"),
                            ("high_end", "数码发烧友"),
                            ("budget", "性价比党"),
                            ("student", "学生群体"),
                        ],
                        default="budget",
                        max_length=20,
                        verbose_name="偏好类型",
                    ),
                ),
                (
                    "loyalty",
                    models.FloatField(default=0.5, verbose_name="品牌忠诚度(0-1)"),
                ),
                (
                    "activity",
                    models.FloatField(default=0.7, verbose_name="活跃度(0-1)"),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="累计消费",
                    ),
                ),
                (
                    "purchase_count",
                    models.IntegerField(default=0, verbose_name="购买次数"),
                ),
            ],
            options={
                "verbose_name": "虚拟顾客",
                "verbose_name_plural": "虚拟顾客",
            },
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(unique=True, verbose_name="模拟天数")),
                (
                    "sales_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="当日销售额",
                    ),
                ),
                (
                    "profit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="当日利润",
                    ),
                ),
                ("order_count", models.IntegerField(default=0, verbose_name="订单数")),
                (
                    "top_product",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="热销商品"
                    ),
                ),
                (
                    "active_events_summary",
                    models.TextField(blank=True, verbose_name="市场事件摘要"),
                ),
                (
                    "report_text",
                    models.TextField(blank=True, verbose_name="AI分析报告"),
                ),
                (
                    "is_ai_generated",
                    models.BooleanField(default=False, verbose_name="是否AI生成"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="生成时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI经营日报",
                "verbose_name_plural": "AI经营日报",
                "ordering": ["-day"],
            },
        ),
        migrations.CreateModel(
            name="DailyStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(unique=True, verbose_name="模拟天数")),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="当日销售额",
                    ),
                ),
                (
                    "total_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="当日利润",
                    ),
                ),
                (
                    "order_count",
                    models.IntegerField(default=0, verbose_name="订单数量"),
                ),
                (
                    "customer_count",
                    models.IntegerField(default=0, verbose_name="活跃顾客数"),
                ),
                (
                    "active_events",
                    models.IntegerField(default=0, verbose_name="活跃事件数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="记录时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "每日统计",
                "verbose_name_plural": "每日统计",
                "ordering": ["day"],
            },
        ),
        migrations.CreateModel(
            name="MarketEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(max_length=100, verbose_name="事件名称"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("demand_boost", "需求激增"),
                            ("demand_drop", "需求下滑"),
                            ("price_up", "价格上涨"),
                            ("price_down", "价格下跌"),
                            ("category_boom", "品类爆发"),
                        ],
                        max_length=20,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "impact_category",
                    models.CharField(
                        choices=[
                            ("all", "全品类"),
                            ("laptop", "笔记本"),
                            ("phone", "手机"),
                            ("headphone", "耳机"),
                            ("monitor", "显示器"),
                            ("gaming", "游戏外设"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="影响品类",
                    ),
                ),
                (
                    "impact_value",
                    models.FloatField(
                        default=20.0,
                        help_text="正数=增长，负数=下降",
                        verbose_name="影响幅度(%)",
                    ),
                ),
                ("duration", models.IntegerField(default=3, verbose_name="持续天数")),
                (
                    "day_triggered",
                    models.IntegerField(default=1, verbose_name="触发天数"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否生效中"),
                ),
                ("description", models.TextField(blank=True, verbose_name="事件描述")),
                (
                    "emoji",
                    models.CharField(
                        default="📢", max_length=10, verbose_name="事件图标"
                    ),
                ),
            ],
            options={
                "verbose_name": "市场事件",
                "verbose_name_plural": "市场事件",
                "ordering": ["-day_triggered"],
            },
        ),
        migrations.CreateModel(
            name="SimulationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_day",
                    models.IntegerField(default=1, verbose_name="当前天数"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新"),
                ),
            ],
            options={
                "verbose_name": "模拟状态",
                "verbose_name_plural": "模拟状态",
            },
        ),
        migrations.CreateModel(
            name="BrandActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(verbose_name="模拟天数")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("price_cut", "降价促销"),
                            ("price_hike", "价格上调"),
                            ("ad_campaign", "广告投放"),
                            ("flash_sale", "限时闪购"),
                            ("new_launch", "新品推广"),
                            ("steady", "维持策略"),
                        ],
                        max_length=20,
                        verbose_name="行动类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="行动描述")),
                (
                    "price_change_pct",
                    models.FloatField(default=0.0, verbose_name="价格变动幅度(%)"),
                ),
                (
                    "sales_impact",
                    models.IntegerField(default=0, verbose_name="销量影响(件)"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="Simulation.brandagent",
                        verbose_name="品牌",
                    ),
                ),
            ],
            options={
                "verbose_name": "品牌行动日志",
                "verbose_name_plural": "品牌行动日志",
                "ordering": ["-day"],
            },
        ),
    ]
