# Generated by Django 4.2.30 on 2026-06-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Simulation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("price_cut", "降价促销"),
                    ("price_hike", "价格上调"),
                    ("ad_campaign", "广告投放"),
                    ("flash_sale", "限时闪购"),
                    ("new_launch", "新品推广"),
                    ("steady", "维持策略"),
                    ("delist", "商品下架"),
                    ("restock", "自动补货"),
                    ("launch", "商品上架"),
                    ("new_product", "AI新品发布"),
                ],
                max_length=20,
                verbose_name="行动类型",
            ),
        ),
    ]
