# Generated by Django 4.2.30 on 2026-06-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Simulation", "0002_alter_brandactionlog_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandagent",
            name="funds",
            field=models.DecimalField(
                decimal_places=2,
                default=100000.0,
                max_digits=14,
                verbose_name="流动资金(元)",
            ),
        ),
        migrations.AddField(
            model_name="brandagent",
            name="is_bankrupt",
            field=models.BooleanField(default=False, verbose_name="是否已破产"),
        ),
    ]
