# Generated by Django 4.2.30 on 2026-06-26 02:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Simulation", "0003_brandagent_funds_brandagent_is_bankrupt"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_reports",
                to="Simulation.brandagent",
                verbose_name="归属品牌",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="day",
            field=models.IntegerField(verbose_name="模拟天数"),
        ),
        migrations.AlterUniqueTogether(
            name="dailyreport",
            unique_together={("brand", "day")},
        ),
        migrations.CreateModel(
            name="BrandDailyStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(verbose_name="模拟天数")),
                (
                    "sales_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="当日销售额",
                    ),
                ),
                (
                    "profit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="当日利润",
                    ),
                ),
                (
                    "order_count",
                    models.IntegerField(default=0, verbose_name="当日订单量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="记录时间"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="Simulation.brandagent",
                        verbose_name="归属品牌",
                    ),
                ),
            ],
            options={
                "verbose_name": "品牌每日统计",
                "verbose_name_plural": "品牌每日统计",
                "ordering": ["day", "brand"],
                "unique_together": {("brand", "day")},
            },
        ),
    ]
