# Generated by Django 4.2.30 on 2026-06-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0002_product_brand_product_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="CostPrice",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="成本价(元)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="DesignScore",
            field=models.IntegerField(default=60, verbose_name="外观评分"),
        ),
        migrations.AddField(
            model_name="product",
            name="PerformanceScore",
            field=models.IntegerField(default=60, verbose_name="性能评分"),
        ),
        migrations.AddField(
            model_name="product",
            name="Specs",
            field=models.JSONField(blank=True, default=dict, verbose_name="规格参数"),
        ),
        migrations.AddField(
            model_name="product",
            name="UtilityScore",
            field=models.IntegerField(default=60, verbose_name="实用性评分"),
        ),
    ]
